### ISSUE TITLE
Testing Transformer Issue

### ISSUE THREAD

**Issue by hung-z** [gustmd0121/Time_is_not_Enough#1]
Thanks for publishing source code, the work is very interesting.
I am running this code for my project however I face issue when run test code for transformer:
        Unexpected key(s) in state_dict: "initial_linear.weight", "initial_linear.bias". 
Can you check the code then fix it?

Thank you.

**Comment by gustmd0121** [comment]
Hello and thank you for your interest in our work. 
There was an error in the code when loading the "initial_linear.weight" and "initial_linear.bias" for the transformer model, and therefore we successfully fixed it.
 Please let us know if the revised version works. 

Thank you.

**Comment by gustmd0121** [comment]
I will close this issue for now. Please reopen if the issue persists.

**Comment by hung-z** [comment]
Thanks for fixing. I still face the issues that since the length of inverted from istft is different from original one, then transformer initial first layer again when applying FIA.

**Comment by hung-z** [comment]
Thanks. I will try to reproduce results. I think it should be fine.
